spring.application.name=aprendiendoSpring
spring.profiles.active=dev

currency-service.url=http://default.Jamones.com
currency-service.username=defaultusername
currency-service.key=defaultkey

spring.datasource.url=jdbc:postgresql://localhost:5432/prspring
spring.datasource.username=postgres
spring.datasource.password=usuario
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect