spring.application.name=aprendiendoSpring
logging.level.org.springframework=debug
spring.profiles.active=dev

currency-service.url=http://default.Jamones.com
currency-service.username=defaultusername
currency-service.key=defaultkey